hostUrl: https://pim-8f53d76134.trial.akeneo.cloud/
auth:
  clientId: 8_66ezeyfxjbgocsk0w4cgokw0k8wooogw44kogwccos4gswo40w
  secret: 49x98j1wqtmosg0okcw48os0kg00o0swoco48o4kos84s8w8w0
  tokenEndPoint: ${hostUrl}/api/oauth/v1/token
  username: postman_1986
  password: 755677568
logging:
  level:
    org.springframework.web: "DEBUG"

api:
  productsEndpoint: ${hostUrl}/api/rest/v1/products
  productModelsEndpoint: ${hostUrl}/api/rest/v1/product-models
